#ifndef TOY_RISCV_KERNEL_KERNEL_DEF_H
#define TOY_RISCV_KERNEL_KERNEL_DEF_H

#ifdef TOY_RISCV_KERNEL_TEST_ALL
#define TOY_RISCV_KERNEL_TEST_MEM_MANAGE 1
#define TOY_RISCV_KERNEL_TEST_SCHEDULER 1
#define TOY_RISCV_KERNEL_PRINT_TASK 1
#endif // TOY_RISCV_KERNEL_TEST_ALL

#ifdef TOY_RISCV_KERNEL_TEST_MEM_MANAGE
#define PRINT_BUDDY_DETAIL 1
#endif // TOY_RISCV_KERNEL_TEST_MEM_MANAGE

#endif //TOY_RISCV_KERNEL_KERNEL_DEF_H
