#ifndef TOY_RISCV_KERNEL_KERNEL_SIGNAL_DEFS_H
#define TOY_RISCV_KERNEL_KERNEL_SIGNAL_DEFS_H

#define NOTHING (0)
#define SIGINT (2)
#define SIGKILL (9)

#endif // TOY_RISCV_KERNEL_KERNEL_SIGNAL_DEFS_H
